//! `curve.*` enrichment facts — Curve stableswap / metapool composition and
//! peg-state reads against the simulated wallet state.
//!
//! Generated by the facts stub scaffolder from `schema/method-catalog.json`
//! (`planned` methods, `server == "sim-server"`, namespace `curve`). The inner
//! [`dispatch`] match is FROZEN at scaffold time: it mirrors the catalog's
//! sim-server registry one arm per method and must never be hand-edited. Devs
//! fill in the per-method `fn` bodies (currently
//! [`FactError::NotImplemented`][super::FactError::NotImplemented]) without
//! touching the dispatch arm set.
//!
//! Param shapes arrive as lowered Cedar values (see the namespace `mod.rs`
//! param helpers), not `simulation-state` shapes.

use serde_json::Value;

use super::FactCtx;
use super::FactError;

/// Dispatch a `curve.*` method against `ctx`. FROZEN — one arm per sim-server
/// method in the catalog `curve` namespace, plus the unknown-method catch-all.
///
/// # Errors
///
/// Returns [`FactError::UnknownMethod`][super::FactError::UnknownMethod] for an
/// unregistered method, or whatever the per-method fn returns (today
/// [`FactError::NotImplemented`][super::FactError::NotImplemented] until the
/// body is implemented).
pub(super) fn dispatch(method: &str, params: &Value, ctx: &FactCtx) -> Result<Value, FactError> {
    match method {
        "curve.imbalance_skew" => imbalance_skew(params, ctx),
        "curve.one_coin_penalty" => one_coin_penalty(params, ctx),
        "curve.pool_depeg_state" => pool_depeg_state(params, ctx),
        "curve.base_pool_depeg" => base_pool_depeg(params, ctx),
        _ => Err(FactError::UnknownMethod(method.into())),
    }
}

/// CURVE-1 (`curve.imbalance_skew`) — how one-sided a Curve stableswap
/// `add_liquidity` is versus the pool's current composition, as a decimal skew
/// (deposit per-coin ratio vs pool per-coin balance ratio).
///
/// readKind: `derived`.
///
/// Params (catalog):
/// - `chain_id`: Long — required.
/// - `action`: Action — required. The proposed Curve `add_liquidity`; per-coin
///   deposit amounts vs the live pool balance ratio.
///
/// Outputs (catalog):
/// - `skew`: decimal — from `$.result.skew`.
///
/// State reads: NONE on `WalletState` — `action.live_inputs.pool_state.balances`
/// and `action.params.tokens` are both action-internal (reducer `live_inputs` /
/// decoded params), folded from the `action` param, not from a wallet accessor.
// BLOCKED: action.live_inputs.pool_state.balances.
//
// The skew = (deposit per-coin ratio) vs (pool per-coin balance ratio) needs the
// live pool balances. `pool_state` IS carried in the reducer action model
// (`PoolState::StableV1 { balances: Vec<U256>, .. }`), but the policy-engine
// lowering for `Amm::AddLiquidity`
// (`crates/policy-engine/src/lowering_v2/amm/add_liquidity.rs`) emits ONLY
// `{ meta, venue, params, currentPrice }` — it drops `live_inputs.pool_state`
// entirely (the sole live_inputs field forwarded is `current_price`). So the
// lowered `action` param that reaches this fact has NO `live_inputs.pool_state`
// key; `action.params.tokens` (the deposit amounts) is present, but without the
// pool balances there is no denominator ratio to compare against. Unblock by
// teaching `add_liquidity` lowering to emit `live_inputs.pool_state.balances`
// (or a dedicated `poolBalances` field) into the Cedar action body.
fn imbalance_skew(_params: &Value, _ctx: &FactCtx) -> Result<Value, FactError> {
    Err(FactError::NotImplemented("curve.imbalance_skew".into()))
}

/// CURVE-2 (`curve.one_coin_penalty`) — the imbalance penalty of a
/// `remove_liquidity_one_coin` withdrawal versus a proportional (balanced) exit,
/// as a decimal fraction (output shortfall vs balanced).
///
/// readKind: `derived`.
///
/// Params (catalog):
/// - `chain_id`: Long — required.
/// - `action`: Action — required. The proposed Curve `remove_liquidity`
///   (`pooled_burn` one-coin variant); burn amount + target coin folded against
///   live pool balances.
///
/// Outputs (catalog):
/// - `penalty`: decimal — from `$.result.penalty`.
///
/// State reads: NONE on `WalletState` — `action.live_inputs.pool_state.balances`,
/// `action.params.lpAmount`, and `action.params.minOut` are all action-internal,
/// folded from the `action` param, not from a wallet accessor.
// BLOCKED: action.live_inputs.pool_state.balances.
//
// The one-coin penalty = (one-coin output shortfall) vs (proportional balanced
// exit) requires the live pool balances to compute the balanced baseline. The
// `Amm::RemoveLiquidity` lowering
// (`crates/policy-engine/src/lowering_v2/amm/remove_liquidity.rs`) emits ONLY
// `{ meta, venue, params, feesOwed }` — it does NOT forward
// `live_inputs.pool_state`. So the lowered `action` param here exposes
// `action.params.lpAmount` (the burn amount) and `action.params.minOut` (the
// declared minimum out set), but NOT the pool balances needed to derive the
// no-penalty proportional output. With only lpAmount + minOut and no pool
// composition, the penalty fraction cannot be computed (minOut is a user-chosen
// slippage floor, not the balanced baseline). Unblock by forwarding
// `live_inputs.pool_state.balances` through the `remove_liquidity` lowering.
fn one_coin_penalty(_params: &Value, _ctx: &FactCtx) -> Result<Value, FactError> {
    Err(FactError::NotImplemented("curve.one_coin_penalty".into()))
}

/// CURVE-3 (`curve.pool_depeg_state`) — live depeg state of a Curve peg pool,
/// emitting TWO context fields from one call: the basis-point peg deviation
/// between the pool's two pegged assets, and whether the pool's current
/// per-coin composition has lurched outside its normal band.
///
/// readKind: `derived`.
///
/// Params (catalog):
/// - `chain_id`: Long — required.
/// - `action`: Action — required. The proposed add/swap on a Curve peg pool;
///   identifies the pool whose two pegged assets + live composition are read.
///
/// Outputs (catalog):
/// - `pegDeviationBp`: Long — from `$.result.pegDeviationBp`.
/// - `compositionOutOfBand`: Bool — from `$.result.compositionOutOfBand`.
///
/// State reads:
/// - composition: `action.live_inputs.pool_state.balances` — action-internal,
///   from the `action` param (no wallet accessor).
/// - per-asset price: `WalletState.tokens` (`BTreeMap`<`TokenKey`, `TokenHolding`>) →
///   `TokenHolding.price_usd` for each pegged asset.
/// - declared peg ref: `TokenHolding.kind.peg_to` — NO accessor exposes the
///   token `kind` / `peg_to` in the Ground accessor list.
// STATE-WORKER ASK: needs TokenHolding::kind() (or a peg_to() accessor) to read TokenKind.peg_to
// BLOCKED: action.live_inputs.pool_state.balances AND TokenHolding.kind.peg_to.
//
// Two independent missing inputs:
//   1. `compositionOutOfBand` needs `action.live_inputs.pool_state.balances` —
//      dropped by the `Amm::AddLiquidity` lowering (see imbalance_skew). The
//      lowered `action` carries no `pool_state`, so the per-coin composition
//      band check has no live balances to test.
//   2. `pegDeviationBp` needs each pegged asset's declared peg target
//      (`TokenHolding.kind.peg_to`) plus its `price_usd`. `price_usd` IS a public
//      field reachable by iterating `ctx.state.tokens`, but `TokenKind.peg_to`
//      lives inside the `Base`/`Wrapped` variants and there is NO accessor in the
//      Ground accessor list (the scaffold's STATE-WORKER ASK). Without it, the
//      fact cannot identify which two assets are "the pegged pair" nor their peg
//      anchors, so the bp deviation between them is uncomputable here.
fn pool_depeg_state(_params: &Value, _ctx: &FactCtx) -> Result<Value, FactError> {
    Err(FactError::NotImplemented("curve.pool_depeg_state".into()))
}

/// CURVE-5 (`curve.base_pool_depeg`) — whether a Curve metapool's underlying
/// base pool (3CRV / crvUSD, …) is depegging: true if ANY base-pool asset is
/// outside its peg band. Decodes the target metapool to its base pool, then
/// folds each base asset's peg ref against its live price.
///
/// readKind: `fold`.
///
/// Params (catalog):
/// - `chain_id`: Long — required.
/// - `action`: Action — required. The proposed metapool `add_liquidity`; the
///   metapool is decoded to its base pool, whose assets' pegs are folded.
///
/// Outputs (catalog):
/// - `basePoolDepeg`: Bool — from `$.result.basePoolDepeg`.
///
/// State reads:
/// - base-pool composition: `action.live_inputs.pool_state` — action-internal,
///   from the `action` param (no wallet accessor).
/// - per-asset price: `WalletState.tokens` (`BTreeMap`<`TokenKey`, `TokenHolding`>) →
///   `TokenHolding.price_usd` for each base-pool asset.
/// - declared peg ref: `TokenHolding.kind.peg_to` — NO accessor exposes the
///   token `kind` / `peg_to` in the Ground accessor list.
// STATE-WORKER ASK: needs TokenHolding::kind() (or a peg_to() accessor) to read TokenKind.peg_to
// BLOCKED: action.live_inputs.pool_state AND TokenHolding.kind.peg_to.
//
// "Is the metapool's base pool depegging?" needs to (a) decode the metapool to
// its base pool and read that base pool's live composition
// (`action.live_inputs.pool_state`) and (b) fold each base asset's peg ref
// (`TokenHolding.kind.peg_to`) against its `price_usd`. Both are unavailable:
//   - `live_inputs.pool_state` is dropped by the `Amm::AddLiquidity` lowering
//     (see imbalance_skew) — the lowered `action` has no pool_state at all, so
//     there is no base-pool composition to fold and no way to enumerate the base
//     assets from the action.
//   - `TokenKind.peg_to` has no accessor (the STATE-WORKER ASK above); even with
//     `price_usd` reachable via `ctx.state.tokens`, the per-asset peg anchor that
//     defines the "band" cannot be read.
// Either gap alone blocks the fold; both are missing.
fn base_pool_depeg(_params: &Value, _ctx: &FactCtx) -> Result<Value, FactError> {
    Err(FactError::NotImplemented("curve.base_pool_depeg".into()))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    // TODO(dev): co-locate `curve.*` fact tests here as bodies are implemented.
    // Mirror the Ground-pass style: build a WalletState fixture (state_with /
    // token_param helpers), call
    // `dispatch("curve.<name>", &params, &FactCtx { state: &state })`, and
    // assert on the `$.result.*` fields named in each fn's doc comment.
}
