/**
 * Protocol resolver registry — `<protocol>:<scope>` → resolver function.
 *
 * Each protocol file (e.g. `aave_v3.ts`) exports its resolver(s) and is
 * imported here to register entries in `PROTOCOL_SOURCE_RESOLVERS`.
 *
 * Add a new protocol:
 *  1. Add the source kind literal to the `ProtocolSourceKind` union in
 *     both `types.ts` (resolver-side) and `build-index.ts` (validator-side).
 *  2. Implement the resolver under `scripts/resolvers/<protocol>.ts`.
 *  3. Register it in the map below.
 *  4. Document it in `registryV2/docs/PROTOCOL_SOURCE_CATALOG.md`.
 */

import {
  atokensResolver,
  variableDebtsResolver,
  stableDebtsResolver,
} from "./aave_v3.ts";
import {
  factoryCrvusdResolver,
  factoryCryptoBaseResolver,
  factoryCryptoResolver,
  factoryTricryptoBaseResolver,
  factoryTricryptoResolver,
  factoryTwocryptoBaseResolver,
  factoryTwocryptoResolver,
  factoryV2Resolvers,
  gaugesResolver,
  stableNgResolvers,
} from "./curve.ts";
import type { ProtocolResolver, ProtocolSourceKind } from "./types.ts";

export { rpcClient } from "./rpc.ts";
export type {
  ProtocolResolver,
  ProtocolResolvedAddress,
  ProtocolSourceKind,
  ResolverOpts,
  Hex,
  CacheEntry,
  RpcClient,
} from "./types.ts";

/** Map from source kind → resolver. Curve StableSwap-NG entries are generated by coin count. */
export const PROTOCOL_SOURCE_RESOLVERS: Record<ProtocolSourceKind, ProtocolResolver> = {
  "aave_v3:atokens": atokensResolver,
  "aave_v3:variable_debts": variableDebtsResolver,
  "aave_v3:stable_debts": stableDebtsResolver,
  "curve:gauges": gaugesResolver,
  "curve:factory_crvusd_2coin_mainnet": factoryCrvusdResolver,
  "curve:factory_crypto_base": factoryCryptoBaseResolver,
  "curve:factory_crypto_mainnet": factoryCryptoResolver,
  "curve:factory_tricrypto_base": factoryTricryptoBaseResolver,
  "curve:factory_tricrypto_mainnet": factoryTricryptoResolver,
  "curve:factory_twocrypto_base": factoryTwocryptoBaseResolver,
  "curve:factory_twocrypto_mainnet": factoryTwocryptoResolver,
  ...Object.fromEntries(factoryV2Resolvers.map((resolver) => [resolver.source, resolver])),
  ...Object.fromEntries(stableNgResolvers.map((resolver) => [resolver.source, resolver])),
} as Record<ProtocolSourceKind, ProtocolResolver>;
